name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update file
        run: |
          echo "Last updated: $(date)" > activity.txt

      - name: Commit changes
        run: |
          git config user.name "Ishaan Verma"
          git config user.email "vermaishaan12345@gmail.com"
          git add .
          git commit -m "chore: daily update" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

